@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title С2 - Secrets

Container(vault, "Secret Store", "Vault", "Хранилище секретов")
Container(vault_agent, "Vault Agent", "Sidecar", "Агент для управления секретами")
Container(kuber, "Kubernetes API", "K8s", "API для управления k8s узлом")
Container(transaction_query_service, "Transaction Query Service", "Java/Spring", "API для read запросов платежей")

Rel(vault_agent, vault, "Получение кредов, проставление JWT токена", "HTTPS")
Rel(vault, kuber, "Авторизация в k8s", "HTTPS")
Rel(vault_agent, transaction_query_service, "Поставка кредов в целевые сервисы", "HTTPS")

@enduml