apiVersion: v1
kind: Secret
metadata:
  name: mtls-certificates
  namespace: payment-system
  labels:
    app: wallet-service
    env: dev
type: kubernetes.io/tls
stringData:
  tls.crt: ""
  tls.key: ""
  ca.crt: ""