@startuml
title Sequence: Подстановка кредов

participant "Vault Agent" as vault_agent
participant "Vault" as vault
participant "Kubernetes API" as kuber
participant "Pod" as pod


kuber -> pod: Запуск пода
pod -> vault_agent: запуск sidecar контейнера

== auth ==
vault_agent -> vault_agent: чтение JWT из файловой системы
vault_agent -> vault: передача JWT
vault -> kuber: Валидация JWT
kuber -> vault: Успешная валидация
vault -> vault_agent: Возвращает vault_token

== подстановка кредов ==
vault_agent -> vault: Получение кердов для пода
vault -> vault_agent: Возвращает креды
vault_agent -> pod: Поставляет файл с кредами
pod -> pod: Загружает файл с кредами в конфигурацию

== rotation ==
vault -> vault_agent: Обновленный vault_token
vault_agent -> vault: Перечитать креды
vault -> vault_agent: Возвращает креды
vault_agent -> pod: Перезаписывает файл с кредами
pod -> pod: hot reload конфига

@enduml