@startuml
title Sequence: Успешная проверка HMAC внешних систем

participant "Payment Provider" as payment_provider
participant "API Gateway" as gateway
participant "Replay Store" as cache
participant "Callback Service" as callback_service

payment_provider -> gateway: Запрос об успешном проведении платежа
gateway -> gateway: Успешная проверка HMAC
gateway -> cache: Получение данных по eventId
cache -> gateway: Данные в кэше не нашлись
gateway -> callback_service: маршрутизация запроса
callback_service -> gateway: Успешнный ответ
gateway -> cache: Запись в кэш с eventId
gateway -> payment_provider: Успешнный ответ
@enduml