apiVersion: v1
kind: Service
metadata:
  name: wallet-service-canary
  namespace: default
  labels:
    app: wallet-service
    role: canary
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: wallet-service